DSEG SEGMENT
	STRING 'HELLO,WORLD',ODH,OAH,'$'
DSEG ENDS
CSEG SEGMENT
	ASSUME DS:DSEG,CS:CSEG
START:  MOV AX,DSGE
		MOV DS,AX
		LEA DX,STRING
		MOV AH,09H
		INT 21H
		MOV AH,4CH
		INT 21H
CSEG ENDS
END START