DATA SEGMENT
	STRING DB 10,0,10 DUP(?)
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE,DS:DATA
START:		MOV AX,DATA
			MOV DS,AX
			LEA DX,STRING
			MOV AH,0AH
			INT 21H
			MOV CL,STRING+1		;QUESTION1
			XOR CH,CH
			ADD DX,CX
			MOV BX,DX
			MOV BYTE PTR [BX+2],'$'	;QUESTION2
			MOV AH,4CH
			INT 21H
CODE ENDS
END START